"""Add created at.

Revision ID: 49638f6967c2
Revises:
Create Date: 2025-01-14 11:57:03.485224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49638f6967c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
